### PR TITLE
feat: add POP opcode

### PR DESCRIPTION
**Pull request by Eikix**
Adding POP opcode in Kakarot

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Add POP opcode
- Still missing: update "supported opcode" list
- Succesfully running tests with new setup

### CODE REVIEW

**Review by 0xMentorNotAPseudo — COMMENTED** [review]
LGTM. Can you just update the supported opcodes and README accordingly please?

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm. Please update supported_opcodes.md and Main readme pie chart section with the new number of opcodes

**Comment by Eikix** [comment]
> Lgtm. Please update supported_opcodes.md and Main readme pie chart section with the new number of opcodes

Done:)!

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm

**Pull request merged**
