### PR TITLE
feat/add_deploy_script

### PR DESCRIPTION
**Pull request by TotalPizza**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [X] Other (please describe):

## What is the current behavior?

Currently the protocol has to be  manually deployed using CLI commands.

Resolves #<Issue number>

- Added python script that performs deployment
- Fixed small make compile error
-

## Other information

Time spent on this PR: 
0.5 days

### CODE REVIEW

**Review by Eikix — COMMENTED** [review]
great PR:)! Did you try to run it locally to deploy Kakarot on testnet2?

Could we dump the contract addresses / tx hashes in a .gitignore'd json file? To be able to retrieve it even if the terminal shuts down?

**Comment by TotalPizza** [comment]
> great PR:)! Did you try to run it locally to deploy Kakarot on testnet2?
> 
> Could we dump the contract addresses / tx hashes in a .gitignore'd json file? To be able to retrieve it even if the terminal shuts down?

Address are now logged to a .gitignored json file.
However, I just noticed that the starknet.py dependency wasn't added to the pyproject.toml file. And it unfortunately can't be because it depends on cairo-lang 0.10.3.
We can't bump cairo-lang as cairo-coverage depends on 0.10.1...and cairo-coverage doesn't appear to be bumpable.
 
Do we still use cairo-coverage?

Most traight forward fix would be:
python `^3.9` -> `>=3.8,<3.10`
remove `cairo-coverage`

**Comment by Eikix** [comment]
> > great PR:)! Did you try to run it locally to deploy Kakarot on testnet2?
> > Could we dump the contract addresses / tx hashes in a .gitignore'd json file? To be able to retrieve it even if the terminal shuts down?
> 
> Address are now logged to a .gitignored json file. However, I just noticed that the starknet.py dependency wasn't added to the pyproject.toml file. And it unfortunately can't be because it depends on cairo-lang 0.10.3. We can't bump cairo-lang as cairo-coverage depends on 0.10.1...and cairo-coverage doesn't appear to be bumpable.
> 
> Do we still use cairo-coverage?
> 
> Most traight forward fix would be: python `^3.9` -> `>=3.8,<3.10` remove `cairo-coverage`

@LucasLvy wdyt?

**Review by Eikix — APPROVED** [review]
lgtm

**Pull request merged**
