### PR TITLE
Comparison & bitwise logic operations : 0x18 XOR, 0x1A BYTE

### PR DESCRIPTION
**Pull request by Riad15l**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Two comparison operations were not implemented: XOR, BYTE

Issue Number: 50

## What is the new behavior?

The two opcodes are now implemented and tested

### CODE REVIEW

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
can you run make format

**Comment by Riad15l** [comment]
> can you run make format

Done

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Pull request merged**
