### PR TITLE
fix ci and readme

### PR DESCRIPTION
**Pull request by ClementWalter**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The CI fails because the auto format cannot commit to main. There is an open discussion about how this should be done (allowing the bot to push to a protected branch is not the right way, see https://github.com/orgs/community/discussions/25305).
This is a quick fix.

## What is the new behavior?

Just applied `make-format` to fix the CI.

## Other information

I've also fixed the build link in the CI and replaced the project owner in all-contributors

### CODE REVIEW

**Review by ClementWalter — COMMENTED** [review]
@all-contributors
please add matthieuauger for mentoring, code, tests
please add seshanthS for code
please add ftupas for code
please add jobez for code

**Comment by ClementWalter** [comment]
@all-contributors please add @matthieuauger for mentoring, code, tests

**Comment by ClementWalter** [comment]
@all-contributors please add @matthieuauger for mentoring, code, test

**Comment by ClementWalter** [comment]
https://github.com/all-contributors please add @matthieuauger for code

**Comment by ClementWalter** [comment]
@all-contributors
please add @matthieuauger for mentoring code test
please add @seshanthS for code
please add @ftupas for code
please add @jobez for code

**Review by Flydexo — APPROVED** [review]

**Review by 0xMentorNotAPseudo — APPROVED** [review]
LGTM!

**Pull request merged**
