### PR TITLE
0x5b JUMPDEST

### PR DESCRIPTION
**Pull request by danilowhk**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Jumpdest opcode implemented 
-
-

### CODE REVIEW

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
The logic of Jumpdest is not implemented in this PR. We should parse the code upfront before execution and have a mapping of valid Jump destinations.

**Comment by TotalPizza** [comment]
> The logic of Jumpdest is not implemented in this PR. We should parse the code upfront before execution and have a mapping of valid Jump destinations.

Are you sure?
I think I would have done it the same way.
In the implementations I've seen you jump to a provided offset with the JUMP opcode and if the opcode at the new pc location is JUMPDEST, then the jump succeeds.

**Comment by abdelhamidbakhta** [comment]
> > The logic of Jumpdest is not implemented in this PR. We should parse the code upfront before execution and have a mapping of valid Jump destinations.
> 
> Are you sure? I think I would have done it the same way. In the EVM implementations I've seen you jump to a provided offset with the JUMP opcode and if the opcode at the new pc location is JUMPDEST, then the jump succeeds.

Well, yes the opcode itself is ok, what I meant is that the full functionality of handling jump destinations is not complete yet. But we discussed together and it is fine to handle it separately.

**Comment by danilowhk** [comment]
Implemented check_jumpdest function on ExecutionContext, it will take the "pc" as parameter and return "1 or 0" depending if its a valid JUMPDEST location or not

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm

**Pull request merged**
